services:
  postgres:
    image: postgres:17
    container_name: modern-connect-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: modern_connect
    ports:
      - "5432:5432"
    volumes:
      - modern-corsair-connect-postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: modern-connect-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - modern-connect-redis_data:/data

volumes:
  modern-corsair-connect-postgres_data:
  modern-connect-redis_data:
