services:
  postgres:
    image: postgres:17
    container_name: modern-connect-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: modern_connect
    ports:
      - "5432:5432"
    volumes:
      - modern-corsair-connect-postgres_data:/var/lib/postgresql/data

volumes:
  modern-corsair-connect-postgres_data:
